### ISSUE TITLE
cannto find module broccoli-filter

### ISSUE THREAD

**Issue by ahnbizcad** [Vestorly/ember-cli-emblem-hbs-printer#10]
Sorry if this is an issue with something else, or noob.

When I try to install emblem, I get this error

ember install:addon ember-cli-emblem-hbs-printer --save
or 
ember install:addon ember-cli-emblem-hbs-printer

I tried installing 
npm install --save broccoli-filter
but even after doing so, the message is the same, before and after.

The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/home/gwho/Rails/personality-tool/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Cannot find module 'ember-cli-version-checker'
Error: Cannot find module 'ember-cli-version-checker'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/gwho/Rails/personality-tool/node_modules/ember-cli-emblem-hbs-printer/index.js:5:15)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Function.Addon.lookup (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/models/addon.js:671:19)
  at /home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/models/addons-factory.js:43:36
  at visit (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
  at visit (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/utilities/DAG.js:21:5)
  at DAG.topsort (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
  at AddonsFactory.initializeAddons (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/models/addons-factory.js:40:9)
  at Project.initializeAddons (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/models/project.js:312:36)
  at Project.eachAddonCommand (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/models/project.js:363:10)
  at module.exports (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/cli/lookup-command.js:46:13)
  at CLI.<anonymous> (/home/gwho/Rails/personality-tool/node_modules/ember-cli/lib/cli/cli.js:30:26)
  at lib$rsvp$$internal$$tryCatch (/home/gwho/Rails/personality-tool/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/gwho/Rails/personality-tool/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/home/gwho/Rails/personality-tool/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/home/gwho/Rails/personality-tool/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)

**Comment by mixonic** [comment]
@ahnbizcad try doing an `rm -rf node_modules/ && npm install`. It looks like you don't have the dependency checker package installer. Pretty un-related to this printer.

**Comment by bantic** [comment]
@ahnbizcad this was an ember-cli issue, unrelated to emblem: https://github.com/babel/ember-cli-babel/issues/33
